### ISSUE TITLE
test all existing functions

### ISSUE THREAD

**Issue by jovo** [neurodata/Graph-Explorer#1]
for all the functions that don't seem to work as expected, 
- generate a list of them, 
- for each, speculate amount of effort from you to make work

then, we'll decide which to fix, and which to depricate.

**Comment by mlee156** [comment]
3D plots seem wonky in general - No idea how long this would take, if you have an example of a 3d graphml file that would be very useful for me to look at

**Comment by mlee156** [comment]
I understand that perplexity is how well a probability model predicts a sample, however I'm not sure how to test the accuracy

**Comment by jovo** [comment]
let's just remove 3D for now.

On Sun, Nov 1, 2015 at 9:52 PM, alee156 notifications@github.com wrote:

> I understand that perplexity is how well a probability model predicts a
> sample, however I'm not sure how to test the accuracy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/Graph-Explorer/issues/1#issuecomment-152896792
> .

## 

the glass is all full:  half water, half air.
neurodata.io
