### ISSUE TITLE
I made a GE docker file.

### ISSUE THREAD

**Issue by alexbaden** [neurodata/Graph-Explorer#16]
What should we do with it?

**Comment by jovo** [comment]
let's go over it tomorrow,
ideally after making dataview pages for each of our projects :)

On Sun, Nov 22, 2015 at 11:42 AM, Alex Baden notifications@github.com
wrote:

> What should we do with it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/Graph-Explorer/issues/16.

## 

the glass is all full:  half water, half air.
neurodata.io
