### ISSUE TITLE
Albert edits

### ISSUE THREAD

**Issue by mlee156** [neurodata/Graph-Explorer#19]
I've made changes to the layout (deleted the stuff that didn't work)

And also added an option for a graph called "generated worm"

I'm not sure if this is exactly what you wanted, but if it is I can do what I did for the rest of the graphs.

**Comment by jovo** [comment]
did you deploy the changes to the server?

On Thu, Feb 4, 2016 at 7:00 AM, alee156 notifications@github.com wrote:

> I've made changes to the layout (deleted the stuff that didn't work)
> 
> And also added an option for a graph called "generated worm"
> 
> I'm not sure if this is exactly what you wanted, but if it is I can do
> what I did for the rest of the graphs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/Graph-Explorer/issues/19.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by mlee156** [comment]
How do you do that?

**Comment by mlee156** [comment]
Also the edits that I've made are a bit informal (For the graph plotter I created I called it "A worm" for example)

**Comment by jovo** [comment]
https://github.com/openconnectome/Graph-Explorer/

On Thu, Feb 4, 2016 at 7:39 AM, alee156 notifications@github.com wrote:

> How do you do that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/Graph-Explorer/issues/19#issuecomment-179809888
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jovo** [comment]
that's ok.

On Thu, Feb 4, 2016 at 7:39 AM, alee156 notifications@github.com wrote:

> Also the edits that I've made are a bit informal (For the graph plotter I
> created I called it "A worm" for example)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/Graph-Explorer/issues/19#issuecomment-179810509
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by mlee156** [comment]
I pushed the changes to github, does that automatically deploy to the server?

**Comment by mlee156** [comment]
How do I log in to brainapps1.neurodata.io?

**Comment by jovo** [comment]
Ask alex

**Comment by alexbaden** [comment]
I pulled on brainapps.
