### ISSUE TITLE
pull fail

### ISSUE THREAD

**Issue by jovo** [neurodata/Graph-Explorer#21]
i tried to pull new updates from marchette onto the server, but this happend:

```jovo@brainapps1:/srv/shinyapps/Graph-Explorer$ git pull
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 8 (delta 7), reused 8 (delta 7), pack-reused 0
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed

```

```

**Comment by alexbaden** [comment]
Fixed.

**Comment by alexbaden** [comment]
( and pulled )

**Comment by jovo** [comment]
thank you!

On Sun, Feb 7, 2016 at 10:57 AM, Alex Baden notifications@github.com
wrote:

> Fixed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/Graph-Explorer/issues/21#issuecomment-181038482
> .

## 

the glass is all full:  half water, half air.
neurodata.io
